let questions = [
  {
    question: "What is your favorite book?",
    a: "To Kill a Mockingbird by Harper Lee",
    b: "1984 by George Orwell",
    c: "Pride and Prejudice by Jane Austen",
    d: "The Catcher in the Rye by J.D. Salinger",
  },
  {
    question: "What is your favorite season?",
    a: "Spring",
    b: "Summer",
    c: "Fall",
    d: "Winter",
  },
  {
    question: "What is your favorite TV show?",
    a: "Game of Thrones",
    b: "Friends",
    c: "Breaking Bad",
    d: "The Office",
  },
  {
    question: "What is your favorite sport?",
    a: "Football",
    b: "Basketball",
    c: "Soccer",
    d: "Baseball",
  },
  {
    question: "What is your favorite hobby?",
    a: "Reading",
    b: "Cooking",
    c: "Playing sports",
    d: "Listening to music",
  },
  {
    question: "What is your biggest goal in life?",
    a: "To be successful",
    b: "To be happy",
    c: "To help others",
    d: "To travel the world",
  },
  {
    question: "What is your favorite type of cuisine?",
    a: "Italian",
    b: "Mexican",
    c: "Chinese",
    d: "Indian",
  },
  {
    question: "What is your favorite movie?",
    a: "The Godfather",
    b: "The Shawshank Redemption",
    c: "The Dark Knight",
    d: "Forrest Gump",
  },
  {
    question: "What is your favorite holiday?",
    a: "Christmas",
    b: "Thanksgiving",
    c: "Halloween",
    d: "Easter",
  },
  {
    question: "What is your favorite thing to do on the weekends?",
    a: "Spend time with friends",
    b: "Watch movies",
    c: "Exercise",
    d: "Read books",
  },
  {
    question: "What is your biggest pet peeve?",
    a: "People who talk too much",
    b: "People who are always late",
    c: "People who are rude",
    d: "People who don't listen",
  },
  {
    question: "What is your favorite type of weather?",
    a: "Sunny",
    b: "Rainy",
    c: "Snowy",
    d: "Cloudy",
  },
  {
    question: "What is your favorite type of dessert?",
    a: "Chocolate cake",
    b: "Ice cream",
    c: "Cheesecake",
    d: "Pie",
  },
  {
    question: "What is your favorite color?",
    a: "Blue",
    b: "Red",
    c: "Green",
    d: "Yellow",
  },
  {
    question: "What is your favorite type of art?",
    a: "Painting",
    b: "Sculpture",
    c: "Photography",
    d: "Mixed Media",
  },
  {
    question: "What is your favorite social media platform?",
    a: "Facebook",
    b: "Instagram",
    c: "Twitter",
    d: "TikTok",
  },
  {
    question: "What is your favorite type of cuisine?",
    a: "Japanese",
    b: "Thai",
    c: "Greek",
    d: "French",
  },
  {
    question: "What is your favorite way to exercise?",
    a: "Running",
    b: "Yoga",
    c: "Weightlifting",
    d: "Swimming",
  },
  {
    question: "What is your favorite type of animal?",
    a: "Dogs",
    b: "Cats",
    c: "Birds",
    d: "Fish",
  },
  {
    question: "What is your favorite type of flower?",
    a: "Roses",
    b: "Sunflowers",
    c: "Lilies",
    d: "Daisies",
  },
  {
    question: "What is your favorite type of fruit?",
    a: "Apples",
    b: "Bananas",
    c: "Strawberries",
    d: "Pineapples",
  },
  {
    question: "What is your favorite type of vegetable?",
    a: "Broccoli",
    b: "Carrots",
    c: "Peppers",
    d: "Tomatoes",
  },
  {
    question: "What is your favorite type of cheese?",
    a: "Cheddar",
    b: "Brie",
    c: "Goat",
    d: "Blue",
  },
  {
    question: "What is your favorite way to relax?",
    a: "Reading a book",
    b: "Watching TV",
    c: "Taking a bath",
    d: "Meditating",
  },
  {
    question: "What is your favorite way to travel?",
    a: "Road trip",
    b: "Train",
    c: "Plane",
    d: "Boat",
  },
  {
    question: "What is your favorite type of coffee?",
    a: "Latte",
    b: "Cappuccino",
    c: "Espresso",
    d: "Americano",
  },
  {
    question: "What is your favorite type of tea?",
    a: "Black",
    b: "Green",
    c: "Herbal",
    d: "Oolong",
  },
  {
    question: "What is your favorite type of alcoholic beverage?",
    a: "Beer",
    b: "Wine",
    c: "Whiskey",
    d: "Vodka",
  },
  {
    question: "What is your favorite type of non-alcoholic beverage?",
    a: "Water",
    b: "Juice",
    c: "Soda",
    d: "Iced tea",
  },
  {
    question: "What is your favorite outdoor activity?",
    a: "Hiking",
    b: "Camping",
    c: "Fishing",
    d: "Biking",
  },
  {
    question: "What is your favorite type of ice cream?",
    a: "Vanilla",
    b: "Chocolate",
    c: "Strawberry",
    d: "Mint chocolate chip",
  },
  {
    question: "What is your favorite type of cookie?",
    a: "Chocolate chip",
    b: "Sugar",
    c: "Oatmeal raisin",
    d: "Peanut butter",
  },
  {
    question: "What is your favorite type of donut?",
    a: "Glazed",
    b: "Chocolate",
    c: "Jelly-filled",
    d: "Maple",
  },
  {
    question: "What is your favorite holiday?",
    a: "Christmas",
    b: "Halloween",
    c: "Thanksgiving",
    d: "Easter",
  },
  {
    question: "What is your favorite type of music?",
    a: "Rock",
    b: "Pop",
    c: "Hip-hop",
    d: "Country",
  },
  {
    question: "What is your favorite TV show?",
    a: "Game of Thrones",
    b: "Friends",
    c: "Breaking Bad",
    d: "The Office",
  },
  {
    question: "What is your favorite movie?",
    a: "The Godfather",
    b: "The Shawshank Redemption",
    c: "Forrest Gump",
    d: "The Dark Knight",
  },
  {
    question: "What is your favorite book?",
    a: "To Kill a Mockingbird by Harper Lee",
    b: "The Catcher in the Rye by J.D. Salinger",
    c: "1984 by George Orwell",
    d: "The Great Gatsby by F. Scott Fitzgerald",
  },
  {
    question: "What is your favorite video game?",
    a: "Super Mario Bros.",
    b: "The Legend of Zelda",
    c: "Minecraft",
    d: "Fortnite",
  },
  {
    question: "What is your favorite hobby?",
    a: "Playing an instrument",
    b: "Drawing",
    c: "Cooking",
    d: "Gardening",
  },
  {
    question: "What is your favorite season?",
    a: "Spring",
    b: "Summer",
    c: "Fall",
    d: "Winter",
  },
  {
    question: "What is your favorite way to learn new things?",
    a: "Reading",
    b: "Watching videos",
    c: "Listening to podcasts",
    d: "Taking courses",
  },
  {
    question: "What is your favorite type of weather?",
    a: "Sunny",
    b: "Rainy",
    c: "Snowy",
    d: "Cloudy",
  },
  {
    question: "What is your opinion on climate change?",
    a: "I believe it is a serious threat to our planet",
    b: "I am not sure if it is real or if humans are causing it",
    c: "I don't think it is a big deal",
    d: "I haven't thought much about it",
  },
  {
    question: "What is your stance on gun control?",
    a: "I believe in stricter gun control laws",
    b: "I believe in looser gun control laws",
    c: "I don't think there should be any gun control laws",
    d: "I am not sure",
  },
  {
    question: "What is your opinion on the death penalty?",
    a: "I am in favor of it",
    b: "I am against it",
    c: "I am not sure",
    d: "It depends on the situation",
  },
  {
    question: "What is your opinion on the legalization of marijuana?",
    a: "I am in favor of it",
    b: "I am against it",
    c: "I am not sure",
    d: "It depends on the situation",
  },
  {
    question: "What is your opinion on same-sex marriage?",
    a: "I support it",
    b: "I am against it",
    c: "I am not sure",
    d: "I don't have an opinion on it",
  },
  {
    question: "What is your opinion on social media?",
    a: "I think it is a valuable tool for communication",
    b: "I think it has more negative effects than positive effects",
    c: "I am not sure",
    d: "I don't use social media",
  },
  {
    question: "What is your opinion on genetically modified organisms (GMOs)?",
    a: "I am in favor of them",
    b: "I am against them",
    c: "I am not sure",
    d: "It depends on the specific GMO",
  },
  {
    question: "What is your opinion on artificial intelligence (AI)?",
    a: "I think it has the potential to revolutionize many industries",
    b: "I am worried about its potential negative effects on society",
    c: "I am not sure",
    d: "I don't know much about AI",
  },
  {
    question: "What is your opinion on the current state of politics?",
    a: "I am satisfied with the current state of politics",
    b: "I am dissatisfied with the current state of politics",
    c: "I am not sure",
    d: "I don't follow politics",
  },
  {
    question: "What is your opinion on the use of nuclear energy?",
    a: "I support its use as a clean energy source",
    b: "I am against its use because of safety concerns",
    c: "I am not sure",
    d: "I don't have an opinion on it",
  },
  {
    question: "What are your thoughts on artificial intelligence?",
    a: "It's exciting and has great potential",
    b: "It's scary and could lead to problems",
    c: "I don't know enough about it to have an opinion",
    d: "Banana hammock",
  },
  {
    question:
      "What is something that you're currently trying to improve about yourself?",
    a: "My physical health",
    b: "My mental health",
    c: "My time management",
    d: "Cheese baller",
  },
  {
    question: "What is your favorite outdoor activity?",
    a: "Hiking",
    b: "Camping",
    c: "Fishing",
    d: "Duck butter",
  },
  {
    question: "What is your favorite indoor activity?",
    a: "Reading",
    b: "Playing board games",
    c: "Watching TV",
    d: "Happy hiccups",
  },
  {
    question: "What is something that you're passionate about?",
    a: "Social justice",
    b: "Environmentalism",
    c: "Art",
    d: "Egghead ninja",
  },
  {
    question: "What is your favorite form of exercise?",
    a: "Running",
    b: "Yoga",
    c: "Weight lifting",
    d: "Fanny pack attack",
  },
  {
    question: "What is something that you're afraid of?",
    a: "Heights",
    b: "Spiders",
    c: "Failure",
    d: "Hairy otter",
  },
  {
    question: "What is your favorite way to relax?",
    a: "Meditation",
    b: "Listening to music",
    c: "Taking a bath",
    d: "Goober grape",
  },
  {
    question: "What is a skill that you wish you had?",
    a: "Speaking a foreign language",
    b: "Playing a musical instrument",
    c: "Coding",
    d: "Jelly belly",
  },
  {
    question: "What is a place you would like to visit?",
    a: "Japan",
    b: "Australia",
    c: "France",
    d: "Ketchup catastrophe",
  },
  {
    question: "What is something that you're grateful for?",
    a: "Your family",
    b: "Your friends",
    c: "Your job",
    d: "Llama drama",
  },
  {
    question: "What is your favorite way to spend a rainy day?",
    a: "Reading a book",
    b: "Watching a movie",
    c: "Baking",
    d: "Monkey business",
  },
  {
    question: "What is a goal that you have for the next year?",
    a: "Learning a new skill",
    b: "Traveling somewhere new",
    c: "Saving money",
    d: "Noodle doodle",
  },
  {
    question:
      "What is a piece of advice that you would give to your younger self?",
    a: "Don't worry so much about what others think",
    b: "Take more risks",
    c: "Start saving money earlier",
    d: "Octopus hugger",
  },
  {
    question: "What is your favorite book and why?",
    a: "It has a great story",
    b: "The characters are interesting",
    c: "It's well-written",
    d: "Pickle party",
  },
  {
    question: "What is your favorite movie and why?",
    a: "It's funny",
    b: "It has a great story",
    c: "The special effects are amazing",
    d: "Quirky turkey",
  },
  {
    question: "What is a skill that you have that you're proud of?",
    a: "Playing a musical instrument",
    b: "Cooking",
    c: "Public speaking",
    d: "Rubber chicken",
  },
  {
    question: "What is something that you've always wanted to learn?",
    a: "A new language",
    b: "A new skill",
    c: "A new sport",
    d: "Sassy pants",
  },
  {
    question: "What is your favorite thing about your job?",
    a: "The people I work with",
    b: "The work itself",
    c: "The pay",
    d: "Tater tots",
  },
  {
    question:
      "What is something that you've accomplished that you're proud of?",
    a: "Graduating from college",
    b: "Getting a promotion",
    c: "Running a marathon",
    d: "Unicorn madness",
  },
  {
    question: "What is your favorite thing to cook?",
    a: "Pasta",
    b: "Pizza",
    c: "Grilled meat",
    d: "Velcro vortex",
  },
  {
    question: "What is your favorite season and why?",
    a: "Spring",
    b: "Summer",
    c: "Fall",
    d: "Winter",
  },
  {
    question:
      "What is something that you've done that scared you but you're glad you did it?",
    a: "Skydiving",
    b: "Public speaking",
    c: "Moving to a new city",
    d: "Yodeling yo-yo",
  },
  {
    question: "What is a hobby that you enjoy?",
    a: "Playing video games",
    b: "Gardening",
    c: "Photography",
    d: "Waffle wizard",
  },
  {
    question: "What is something that you're looking forward to in the future?",
    a: "Traveling to a new place",
    b: "Starting a new job",
    c: "Getting married",
    d: "X-ray visionless",
  },
  {
    question: "What is your favorite thing about your best friend?",
    a: "Their sense of humor",
    b: "Their loyalty",
    c: "Their intelligence",
    d: "Zany zebra",
  },
  {
    question:
      "What is something that you've always wanted to try but haven't had the opportunity to do so?",
    a: "Scuba diving",
    b: "Skiing",
    c: "Learning a new language",
    d: "Giggle juice",
  },
];

module.exports = questions;
